### ISSUE TITLE
"Homepage" URL in SonarQube Marketplace not working

### ISSUE THREAD

**Issue by alixwar** [SonarSource/sonar-css#106]
**SonarQube version:** 6.7.4 LTS
**Plugin version:** 1.0

**Steps to reproduce:**
- Go to Administration / Marketplace
- Press "Homepage" (link to: http://redirect.sonarsource.com/plugins/css.html )

**Expected:**
URL works

**Actual:**
Not Found
The requested URL /plugins/css.html was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by agigleux** [comment]
Thanks for the feedback. It's fixed now.
