### ISSUE TITLE
Support Vue.js Single File Components

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-css#109]
The structure of a .vue file following the [Single File Components](https://vuejs.org/v2/guide/single-file-components.html) pattern is made of:

`<template>`
`some HTML like here`
`</template>`

`<script>`
`some JS code here`
`</script>`

`<style>`
`some CSS here`
`</style>`

SonarCSS should analyzer the content of the <style> tag.
The <script> is already analyzed by SonarJS thanks to https://github.com/SonarSource/SonarJS/issues/576

Example of OS projects relying on Vue.js: https://github.com/vuejs/awesome-vue#open-source
File Example following the Single File Components pattern: https://github.com/Vuedo/vuedo/blob/master/resources/assets/js/components/Users.vue

**Comment by blowsie** [comment]
This is very similar to this request;
https://github.com/SonarSource/sonar-css/issues/86

They essentially both need to support the `<style>` tag.

Are there any plans to implement?

I could create a PR if i knew where to start 👍

**Comment by vilchik-elena** [comment]
fixed by #86
