### ISSUE TITLE
FP S4662: @extend in Sass

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#135]
```
.success {
  @extend %message-shared;
  border-color: green;
}
```

https://sass-lang.com/guide

`extend` should be added to list of exclusions

**Comment by gvkhirwadkar** [comment]
Hey @vilchik-elena  Just want to know this issue for @extend as unknown rule can be solved if we upgrade sonarqube version ?

**Comment by vilchik-elena** [comment]
@gvkhirwadkar yep, latest sonarqube includes latest versions of analyzers
