### ISSUE TITLE
CSS Modules - @value

### ISSUE THREAD

**Issue by alexmaitken** [SonarSource/sonar-css#146]
We use css modules and use the `@value` like https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md

It currently produces a lot of errors in sonarqube. Is there any way to fix this - or has it been fixed?

**Comment by mattmoskwa** [comment]
We have a similar issue with `composes` https://github.com/css-modules/css-modules/blob/master/docs/composition.md

We've just been ignoring the sonar generated issues, but it would be nice if sonar could understand the css modules keywords.

**Comment by kmcrawford** [comment]
PR creted https://github.com/SonarSource/sonar-css/pull/153
