### ISSUE TITLE
Doesn't support CSS module :export blocks

### ISSUE THREAD

**Issue by slikts** [SonarSource/sonar-css#149]
CSS modules implement `:export` and `:import` pseudo-selectors, and using them like this:
```css
:export {
  exportedKey: exportedValue;
}
```
Creates this error:
```
Unexpected unknown property "exportedKey"
```

**Comment by slikts** [comment]
Adding a stylelint rule as per #140 doesn't have an effect:
```
      "selector-pseudo-class-no-unknown": [true, {
        "ignorePseudoClasses": ["global", "export", "import", "local"]
      }]
```
Running stylelint manually confirms that the rule is picked up, though.

**Comment by slikts** [comment]
Here's an example project where this issue is occuring: https://sonarcloud.io/project/issues?id=code-examples
Source: https://github.com/slikts/code-examples

The stylelint rules are set in `package.json`.

**Comment by vilchik-elena** [comment]
@slikts SonarQube does not look at your stylelint config, in #140 internal stylelint configuration is mentioned. 

I created this ticket #152 to fix your problem

**Comment by slikts** [comment]
What is the reason for not using the local config of a project?

**Comment by vilchik-elena** [comment]
It's made to be used in isolation from Stylelint. If you are using Stylelint, it will probably make more sense for you to import its report, see documentation on it [here](https://docs.sonarqube.org/display/PLUG/Importing+StyleLint.io+Issues+Report). You will need to deactivate CSS rules in SonarQube to not have duplicates.

**Comment by slikts** [comment]
> It's made to be used in isolation from Stylelint.

Right, but the question is, why would it be made that way, i.e., why ignore the existing and correct (for the project) config.

**Comment by vilchik-elena** [comment]
The goal that SonarCSS is usable for a project **not using** Stylelint. Indeed for projects using Stylelint we could provide a better integration than just import of issues report, but for now we don't want to invest there.

**Comment by kmcrawford** [comment]
PR added to support `export` & `import` https://github.com/SonarSource/sonar-css/pull/153
