### ISSUE TITLE
Font declarations should contain at least one generic font family should allow ignores

### ISSUE THREAD

**Issue by Christian24** [SonarSource/sonar-css#150]
Hi,

the rule "Font declarations should contain at least one generic font family" is generally very helpful. However, it would be nice to be able to define exceptions for the rule for icon fonts such as FontAwesome. For icon fonts like FontAwesome no generic font family exists, so it would be great if they could be excluded from the rule.

**Comment by vilchik-elena** [comment]
This rule is taking its implementation from [stylelint](https://stylelint.io/user-guide/rules/font-family-no-missing-generic-family-keyword/), so we can't change it directly. A nice option for you will be to [request this feature](https://github.com/stylelint/stylelint/issues/new?template=REQUEST_A_FEATURE.md) to Stylelint itself.
