### ISSUE TITLE
Avoid false-positive due to CSS Modules specific syntax

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#152]
Some rules produce FPs when [CSS modules](https://github.com/css-modules/css-modules) are used (see #149).
* unknown pseudo-selectors
* unknown properties
 
We should hardcode CSS modules keywords in related rules and/or make these rules configurable by users.

**Comment by kmcrawford** [comment]
PR created as we too are having the same issues. https://github.com/SonarSource/sonar-css/pull/153

**Comment by vilchik-elena** [comment]
fixes #149

**Comment by vilchik-elena** [comment]
https://github.com/css-modules/icss

**Comment by vilchik-elena** [comment]
Syntaxes to support:
* `@value` (rule `S4662`/ `at-rule-no-unknown`), [ref](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md), reported in #146 
* `composes` (rule `S4654`/ `property-no-unknown`), [ref](https://github.com/css-modules/css-modules/blob/master/docs/composition.md), reported in #146 (see second commend)
*
