### ISSUE TITLE
Error during SonarQube Scanner execution - Timeout Issue

### ISSUE THREAD

**Issue by senthilpandy** [SonarSource/sonar-css#154]
am facing the issue: Can not execute Findbugs with a timeout threshold value of 600000 milliseconds
This issue encountered after added Findbugs plugin into sonarqube.
When i remove the findbugs plugin from sonarqube it worked.
Note: Its not a huge files only scanning 1 java package [6 Java files]

sonarqube-6.7.6
Findbugs 3.9.2
Java 1.8

**With 600000 Timeout:**
INFO: 0/0 source files have been analyzed
INFO: Sensor JavaSquidSensor [java] (done) | time=7560ms
INFO: Sensor FindBugs Sensor [findbugs]
INFO: Loading findbugs plugin: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs/findsecbugs-plugin.jar
INFO: Findbugs output report: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs-result.xml
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 10:24.412s
INFO: Final Memory: 2880M/3730M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Can not execute Findbugs with a timeout threshold value of 600000 milliseconds
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**With 7200000 Timeout:**
01:27:46.920 INFO: Findbugs output report: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs-result.xml
02:13:27.194 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 17,253ms last 8 cycles average is 2,156ms
02:20:46.420 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 7,385ms last 8 cycles average is 3,079ms
02:25:49.816 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 37,048ms last 8 cycles average is 7,711ms
02:32:20.710 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 26,867ms last 8 cycles average is 11,069ms

The above issue persist in following combination also.
sonarqube-7.6
Findbugs 3.10.0 / SpotBugs. 3.1.11

Is there any Fix / Workaround available?

**Comment by vilchik-elena** [comment]
Please report your problem at https://community.sonarsource.org as it has nothing to do with CSS analyzer
