### ISSUE TITLE
Support Stylelint issue report in UTF-16

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#164]
Reported in #161

**Comment by SomethingNew71** [comment]
This is still an issue using 
- sonar-css version 1.2.1 
- sonarqube 8.5.1 
- node 12.18.3
- sonar-scanner 3.1.0

I have tried changing the encoding and line endings of the stylelintrc, I have tried different file names (eg. .stylelintrc, .stylelintrc.json, and .stylelintrc.js). None of these have provided a solution and I am at my wit's end trying to get this running in our enterprise application. 

Any idea why this is still happening?
