### ISSUE TITLE
Process never returns after deploying bundle

### ISSUE THREAD

**Issue by SpaceGerbil** [SonarSource/sonar-css#167]
I am using:
sonar-scanner-ant: 2.5
sonar-scanner-windows: 3.3.0.1494
Sonar Qube: 7.7 
Node.js: 10.15.1
sonarCSS: 1.0.3

I am having an issue trying to run the CSS analysis on my java project. Everything works great until I get to the point where the sonarCSS sensor is invoked. Turing on verbose logging, this is essentially the last thing I see:

`[sonar:sonar] Sensor SonarCSS Metrics [cssfamily]`
`[sonar:sonar] Sensor SonarCSS Metrics [cssfamily] (done) | time=2897ms`
`[sonar:sonar] Sensor SonarCSS Rules [cssfamily]`
`[sonar:sonar] Checking node version`
`[sonar:sonar] Using Node.js v10.15.1`
`[sonar:sonar] Deploying bundle to C:\Development\myJavaProject\.sonar`

It can run for hours on end without any output back to the log. I can see from my task manager that there is a Node.js thread running and it is consistently busy. At no point does it terminate or slow down it's resource usage. 
I can also confirm that it appears the unzipping of the bundle into the .sonar project has completed. No timestamps on any files are ever updated, nor no new files created in the scanner-report directory either after this point.

If I kill the Node.js thread, I get the usual "Analysis didn't terminate normally" message, and the scanner continue on to other sensors without issue.

Any ideas why this just "hangs"? We only have ~400 .css/.scss/.less files in the project.

**Comment by vilchik-elena** [comment]
@SpaceGerbil 
That's probably a stylelint analysis under the hood which is stuck. Do you think you could provide your css files so that I could debug (zip and attach to the comment here)?
If not, you could play with exclusions to define file(s) causing this problem (I suspect you have some unusual construct making analysis stuck).
Also can you confirm that there is a file `C:\Development\myJavaProject\.sonar\css-bundle\stylelintconfig.json`? what is its content?

**Comment by SpaceGerbil** [comment]
@vilchik-elena 
Thanks for the suggestions. After playing around for some time with the exclusions, I have found that if my project is scanned with sonar.css.file.suffixes set to ONLY .css, it works fine. If sonar.css.file.suffixes is set to ONLY .less, it works fine. If .css and .less are scanned together, the process hangs. While my project has considerably more .css files, we can limp ahead with just looking at those. I would still like to try to understand why to combination of the two results in the process hanging. 

Here is my stylelintcconfig.json

```
{
	"rules": {
		"block-no-empty": true,
		"string-no-newline": true,
		"comment-no-empty": true,
		"function-linear-gradient-no-nonstandard-direction": true,
		"media-feature-name-no-unknown": true,
		"color-no-invalid-hex": true,
		"font-family-no-duplicate-names": true,
		"no-duplicate-at-import-rules": true,
		"no-empty-source": true,
		"declaration-block-no-duplicate-properties": [true, {
			"ignore": ["consecutive-duplicates-with-different-values"]
		}],
		"selector-type-no-unknown": true,
		"at-rule-no-unknown": [true, {
			"ignoreAtRules": ["at-root", "content", "debug", "each", "else", "error", "for", "function", "if", "include", "mixin", "return", "warn", "while", "extend"]
		}],
		"no-duplicate-selectors": true,
		"font-family-no-missing-generic-family-keyword": true,
		"no-extra-semicolons": true,
		"no-invalid-double-slash-comments": true,
		"selector-pseudo-element-no-unknown": true,
		"selector-pseudo-class-no-unknown": [true, {
			"ignorePseudoClasses": ["local", "global"]
		}],
		"keyframe-declaration-no-important": true,
		"function-calc-no-unspaced-operator": true,
		"property-no-unknown": true,
		"declaration-block-no-shorthand-property-overrides": true,
		"unit-no-unknown": true
	}
}
```

**Comment by vilchik-elena** [comment]
Do you think you could provide a reproducer?
