### ISSUE TITLE
Use the imported stylelint report only

### ISSUE THREAD

**Issue by jaysoo** [SonarSource/sonar-css#168]
Is it possible to report only the errors provided by our own stylelint report?

We basically want to use out own custom stylelint rules, but we don't want to have to manage Quality Profiles in SonarQube to disable the same rules there.

**Comment by jaysoo** [comment]
Nevermind, I read up on what the import is supposed to do and it looks like the only way to disable the checks is through Quality Profiles.

**Comment by vmesafernandez** [comment]
Hi, I have read this problem and it closely resembles what I want. 
In the end, were you able to solve it? I don't know why the stylelint report isn't recognizing me :(
