### ISSUE TITLE
S4670: add parameter for ignored types

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#181]
In #151 there was reported an exception for Angular Material, and we hardcoded that exception in the plugin. Yet there are other libraries declaring types (e.g. [FontAwesome](https://community.sonarsource.com/t/css-s4670-the-use-of-fontawesome-raises-a-issue/10114)), so probably it makes sense to expose that parameter to the user.

**Comment by vilchik-elena** [comment]
Same requested [here](https://community.sonarsource.com/t/allow-adding-custom-selectors-for-css-s4670/8594)

**Comment by Saucistophe** [comment]
@vilchik-elena How timely, I just had the problem :)
How exactly do you enable this rule?
I tried adding `sonar.css.ignoreTypes=/^myPrefix-/` to my sonar-project.properties, to no avail.

**Comment by vilchik-elena** [comment]
@Saucistophe indeed it will not work
You need to do it in SonarQube UI. Go to Rules tab, find this rule and edit parameter value for the profile you use for your project(s).

**Comment by Saucistophe** [comment]
Thanks for your quick response, worked like a charm!

**Comment by josersleal** [comment]
> @Saucistophe indeed it will not work
> You need to do it in SonarQube UI. Go to Rules tab, find this rule and edit parameter value for the profile you use for your project(s).
@vilchik-elena : it does not seem possible to edit the rule as it is not a custom rule
Any steps to do so in more detail are appreciated

**Comment by agueguenpro** [comment]
How should we update this parameter ? I can't see any parameter for the rule css:S4660 and can't edit it.

**Comment by vilchik-elena** [comment]
@heolcroa it's not yet released, should be the case next week

**Comment by dlorenzo** [comment]
Is there currently any way of changing this parameter from a sonar-project.properties file?

**Comment by vilchik-elena** [comment]
@dlorenzo nope, only UI

**Comment by JerinJ** [comment]
@vilchik-elena 
How can we ignore `ng-deep` from sonar, in css file.

**Comment by vilchik-elena** [comment]
@JerinJ it should be ignored by default (SonarCSS 1.1 is required). If something does not work for you please take a trouble to start a proper thread in https://community.sonarsource.com/

**Comment by adrianagdi** [comment]
@vilchik-elena 
We have a central SonarQube server for multiple projects, and we would like to be able to configure ignoreTypes per project so each project can use their own prefixes for custom elements.
Are there any plans for the future to make this configurable in sonar-project.properties file?
Or do we need to wait for https://github.com/SonarSource/sonar-css/issues/265?
