### ISSUE TITLE
False positive for Ionic 4 selectors

### ISSUE THREAD

**Issue by untilbit** [SonarSource/sonar-css#187]
Same as #151 but for Ionic 4 selectors.

**Comment by vilchik-elena** [comment]
Thanks to https://github.com/SonarSource/sonar-css/issues/181 there is a parameter now (check new version 1.1)

**Comment by untilbit** [comment]
Awesome!

Is this feature in latest SonarQube  as of today?

**Comment by vilchik-elena** [comment]
Yep, in SQ 7.8 (released yesterday)

**Comment by untilbit** [comment]
Ok. Close the issue.

**Comment by Ismaestro** [comment]
Nicee!! Thanks @vilchik-elena !
