### ISSUE TITLE
Downgrade micromatch dependency

### ISSUE THREAD

**Issue by prochafilho** [SonarSource/sonar-css#194]
SonarCSS has a prerequisite on node >= 6. However, stylelint 10.1.0 depends on `micromatch: ^4.0.0`, that range is a problem. Micromatch current implementation uses the following syntax:
` let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);`

On another words, it uses Object spread operator, that is _not_ supported by node 6. The maintainers of micromatch recommend downgrade to 3.x.x, as you can see [here](https://github.com/micromatch/micromatch/issues/159). This syntax is not compatible with all versions of JS, especially, the version displayed on the documentation for [SonarCSS](https://docs.sonarqube.org/display/PLUG/Sonarcss).

What can we expect from Sonar?

**Comment by vilchik-elena** [comment]
@prochafilho Indeed we missed that stylelint bumped required NodeJS version to >=8.7.0. As far as I can see the only thing we can do (apart from downgrading stylelint) is to increase our requirement for NodeJS. This seems reasonable as NodeJS 6 is not supported anymore

**Comment by vilchik-elena** [comment]
P.S. We should have integration tests using different versions of Node

**Comment by dmarkhas** [comment]
> As far as I can see the only thing we can do (apart from downgrading stylelint) is to increase our requirement for NodeJS

Can you please do both? i.e. release a version that is compatible with Node 6 as well as a newer version that requires Node > 8.7 ?

**Comment by vilchik-elena** [comment]
@dmarkhas if you want version compatible with Node 6, use SonarCSS 1.0.x release

**Comment by prochafilho** [comment]
@vilchik-elena using SonarCSS 1.0.x release works for me. Thank you.

**Comment by vilchik-elena** [comment]
We already require Node v8 (see https://docs.sonarqube.org/latest/analysis/languages/css/)
