### ISSUE TITLE
Add parameter for css:S4660 to define custom pseudo-element selectors with "ng-deep" by default

### ISSUE THREAD

**Issue by reitzmichnicht** [SonarSource/sonar-css#196]
Please add an option to specify a regex to allow custom selectors like ::ng-deep for this rule.

**Comment by colin-mueller-sonarsource** [comment]
+1 from a support customer

**Comment by jah434s** [comment]
Also needed for Custom Elements

**Comment by Rychu-Pawel** [comment]
Isn't this what you are looking for: https://github.com/SonarSource/sonar-css/issues/181#issuecomment-506662130 ?

**Comment by Rychu-Pawel** [comment]
@jah434s isn't this what you are looking for: https://github.com/SonarSource/sonar-css/issues/181#issuecomment-506662130

**Comment by ddzingielewski** [comment]
Hi, is this exclusion for ng-deep is available in SonarQube Version 7.9.5 (build 38598)? 
My sonar is still complains with message: Unexpected unknown pseudo-element selector "::ng-deep"
I do not see to create any custom exclusion in css:s4660:
![obraz](https://user-images.githubusercontent.com/60173807/125927682-b6a06e80-ab15-4643-9042-84ecf1f80455.png)

best regards
Darek

**Comment by vilchik-elena** [comment]
@ddzingielewski Nope, you should update to new LTS 8.9
