### ISSUE TITLE
Unexpected unknown type selector "last-child"

### ISSUE THREAD

**Issue by enaether** [SonarSource/sonar-css#205]
Sonar-css is also parsing scss files. In scss files valid type selectors are marked as failures: Unexpected unknown type selector "last-child"
E. g. div:first-child:not(last-child)

It should either ignore scss files, if only css files are actually wanted to be analyzed. Or please support //NOSONAR comment to be able to skip such lines.

**Comment by vilchik-elena** [comment]
Hi,

I can't reproduce. Please provide code sample reproducing FP for you and also version of css analyzer.

**Comment by andrea-guarino-sonarsource** [comment]
closing the issue due to inactivity and lack of reproducer.
