### ISSUE TITLE
Invalid filename '<input css 1>' for CssSyntaxError

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#208]
See details https://community.sonarsource.com/t/error-on-css-linting/13130/22

I believe we should check that `source` property holds a real path before passing it to `FileSystem` ([here](https://github.com/SonarSource/sonar-css/blob/124ea56a39eb77ec1019fd3ffd8d0de79f960704/sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java#L170)).

**Comment by poplevente** [comment]
any update on this?

**Comment by rtaylor72** [comment]
I'm also interested in this fix... Does 8.0 version address this?

https://community.sonarsource.com/t/error-on-css-linting/13130/24

I do have '//**' in my code, but it is in a third party library I have no control over (Bootstrap 3.1.1 library in the variables.less file)

**Comment by poplevente** [comment]
any update on this? we would really like to get rid of this issue

**Comment by Shmow** [comment]
> any update on this? we would really like to get rid of this issue

Replace //** from any (s)css/less file in your solution (also from 3rd party libs). That fixed it for us.

**Comment by poplevente** [comment]
> 
> 
> > any update on this? we would really like to get rid of this issue
> 
> Replace //** from any (s)css/less file in your solution (also from 3rd party libs). That fixed it for us.

can't do that. we use several npm packages, which gets installed in vsts on build. this needs to be resolved by the sonar guys. not sure what's taking so long ... we pay for a reason for their service ...

**Comment by vilchik-elena** [comment]
Sorry for taking so long, we should tackle this problem next week

**Comment by vilchik-elena** [comment]
Probably the source of this mysterious `<input ccs 1>`
https://github.com/stylelint/stylelint/blob/master/lib/createStylelintResult.js#L79

**Comment by rtaylor72** [comment]
How is this a fix for us?

**Comment by vilchik-elena** [comment]
sorry, it's not a fix, just a note after some investigation

**Comment by poplevente** [comment]
It's almost 2 weeks gone again, but no fix. when can we expect this to be fixed?

**Comment by vilchik-elena** [comment]
fixed by https://github.com/SonarSource/sonar-css/pull/221 (https://github.com/SonarSource/sonar-css/pull/221/files#diff-403b38dfb8f458e61b61c95013a93807R80-R86)

**Comment by poplevente** [comment]
@vilchik-elena i think you should close a bug, once it's released, maybe there was a fix, but i don't see it released and we still got the error within VSTS
