### ISSUE TITLE
Rule S4660 should ignore ::v-deep in Vue files

### ISSUE THREAD

**Issue by kpwbo** [SonarSource/sonar-css#247]
::v-deep is a deep selector similar to ng-deep that can be used in the style tags of .vue files. I think it should be ignored by default when the analyzed file is a .vue file.
Reference: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors
Example:
![image](https://user-images.githubusercontent.com/5074608/72570664-7ef7cc80-388b-11ea-93a6-c65a835f8c57.png)

**Comment by vilchik-elena** [comment]
👍 
While this ticket is not implemented you can configure the rule to ignore this selector in your profile

**Comment by rijkvanzanten** [comment]
@vilchik-elena default support for `::ng-deep` was added in https://github.com/SonarSource/sonar-css/pull/220. Would you accept a PR to add `::v-deep` here as well?

> .. you can configure the rule ..

Mind sharing where / how?

**Comment by IGx89** [comment]
@rijkvanzanten to add `::v-deep` you'll need to create a new CSS quality profile that extends from the default `Sonar way`, change your project to use it, then look up the the rule and click Change next to the new profile. You'll then see a pop-up like the following that will allow you to add it:

![image](https://user-images.githubusercontent.com/282698/91347297-b4608300-e7a7-11ea-8f9b-493041675661.png)

Important thing to note, which tripped me up at first (and brought me here), is that you must put `v-deep` and NOT `::v-deep` in the list.

Also, 👍🏻  from me too for SonarSource making v-deep ignored by default. If they're ignoring Angular's by default they should be ignoring Vue's as well, given how popular it also is.
