### ISSUE TITLE
Rule css:S4654 is triggered on mso- properties

### ISSUE THREAD

**Issue by olsh** [SonarSource/sonar-css#248]
Rule `css:S4654` triggers on `mso-` properties, like `mso-line-height-rule`.
Probably properties with `mso-` prefix should be ignored?

**Comment by vilchik-elena** [comment]
Indeed, we should add parameter to the rule to make it possible to configure such cases

**Comment by dominiquevienne** [comment]
Hi, 
Any news on this topic? I'd love to get the rule update working in my sonar instance
