### ISSUE TITLE
ERROR: SyntaxError: Unexpected token ? in JSON at position 0

### ISSUE THREAD

**Issue by Indigo744** [SonarSource/sonar-css#250]
Hello,

I have a minor issue when running the analysis on our code. SonarCSS seems to always choke on the file `webpack-profile.html` with the message `SyntaxError: Unexpected token ? in JSON at position 0` (see complete log below).

This file is generated using the module [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) (export as a static HTML file).

This is **not** a blocking issue : the analysis continue just fine and finish without further issue.
Also, I am able to ignore this file using the _Source File Exclusions_ parameter.

But I though I should still let you know so maybe you can fix / improve your tool.

Have a nice day.

### Version info

SonarQube version: 8.1.0.31237
SonarCSS version: 1.2 (build 1325)

Visual Studio version: 2017 (15.9.13)
TFS version: 2018 (16.131.28601.4)
sonar-scanner-vsts version: 4.8.0

### Logs (with DEBUG)

``````
INFO: Sensor SonarCSS Metrics [cssfamily]
INFO: 5/5 source files have been analyzed
INFO: Sensor SonarCSS Metrics [cssfamily] (done) | time=1234ms
INFO: Sensor SonarCSS Rules [cssfamily]
DEBUG: css-bundle server is up, no need to start.
INFO: 58 source files to be analyzed

<<other statements omitted for clarity>>

DEBUG: '<solution>/<project>/webpack-profile.html' generated metadata with charset 'UTF-8'
DEBUG: Analyzing D:\Agent\_work\3\s\<solution>\<project>\webpack-profile.html
##[error]ERROR: SyntaxError: Unexpected token ? in JSON at position 0
ERROR:     at JSON.parse (<anonymous>)
ERROR:     at Object.parseSourceMapInput (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\source-map\lib\util.js:433:15)
ERROR:     at new SourceMapConsumer (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\source-map\lib\source-map-consumer.js:17:22)
ERROR:     at PreviousMap.consumer (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss\lib\previous-map.js:69:28)
ERROR:     at new Input (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss\lib\input.js:93:22)
ERROR:     at parseStyle (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss-syntax\parse-style.js:118:10)
ERROR:     at processor (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss-syntax\processor.js:26:9)
ERROR:     at Object.parse (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss-syntax\parse.js:25:10)
ERROR:     at new LazyResult (D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\node_modules\postcss\lib\lazy-result.js:60:16)
ERROR:     at D:\Agent\_work\3\.sonarqube\out\.sonar\mod44\css-bundle\node_modules\stylelint\lib\getPostcssResult.js:123:19
DEBUG: Found 0 issue(s)

<<other statements omitted for clarity>>

INFO: 58/58 source files have been analyzed
INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=1230ms
```

**Comment by andrea-guarino-sonarsource** [comment]
Hi @Indigo744 , 
Sorry for the big delay.
Is the issue still relevant? If so, could you please include the content of the file causing the syntax error (i.e. `webpack-profile.html`)? 
Thanks!

**Comment by Indigo744** [comment]
I'm not sure since we are now excluding this file from analysis.

In any case, I won't be able to give you this file as it contains private information...

You could try to generate a similar file from a webpack demo project and see if you can reproduce the issue.

**Comment by andrea-guarino-sonarsource** [comment]
I managed to reproduce the issue with the following steps:
1. clone https://github.com/ruanyf/webpack-demos/tree/master/demo01
2. `npm install`
3. `npx webpack --profile --json > stats.json`
4. `npx webpack-bundle-analyzer -m static stats.json`
5. analyse generated `report.html` file.


SonarCSS is using `stylelint` under the hood, which in turn uses `postcss`. The syntax error comes from `postcss` library.
There is already this ticket open on `stylelint`: https://github.com/stylelint/stylelint/issues/4282

When it will be fixed, we will be able to upgrade our `stylelint` dependency and it should solve this problem.

**Comment by Indigo744** [comment]
Nice job 👍  sorry I wasn't able to help more. Thanks for your work, I love SonarQube 😸
