### ISSUE TITLE
AT-Rule of Sass @Use 

### ISSUE THREAD

**Issue by wakm** [SonarSource/sonar-css#252]
Similar as in issue #135 the `@Use` at rule of sass should be supported
e.g. in angular style.scss

`@use 'variables;
.test{
 color: variables.myColor;
}
`
see documentation [@Use](https://sass-lang.com/documentation/at-rules/use)

`@Use` should be added to list of exclusions

**Comment by greenstevester** [comment]
> Similar as in issue #135 the `@Use` at rule of sass should be supported
> e.g. in angular style.scss
> 
> `@use 'variables; .test{ color: variables.myColor; } `
> see documentation [@Use](https://sass-lang.com/documentation/at-rules/use)
> 
> `@Use` should be added to list of exclusions

+1 for this, since we've had to disable css at-rules until this is added

**Comment by wakm** [comment]
@greenstevester we use a custom quality profile, so i  were able to add a exclusion manually to the at-rule, maybe this helps you too instead of disabling at-rules

**Comment by vilchik-elena** [comment]
Hi,

Added this to the next milestone, and indeed as @wakm said in previous comment you can always configure the rule yourself (for that you need custom profile).
