### ISSUE TITLE
how to configure the plugin in sonarqube?

### ISSUE THREAD

**Issue by suoha666** [SonarSource/sonar-css#256]
if we want to scan java code in sonarque,we should configue like:
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=./
……
so how to configure this plugin?

**Comment by vilchik-elena** [comment]
Hi,

Please address your problem in [SonarSource Community Forum](https://community.sonarsource.com/) (and try to be more specific about your problem), use "Get Help" category.
