### ISSUE TITLE
Unexpected unknown property "content-visibility", "contain-intrinsic-size"

### ISSUE THREAD

**Issue by fabienbranchel** [SonarSource/sonar-css#264]
`content-visibility` and `contain-intrinsic-size` came with Chrome 85 and are not support.

![image](https://user-images.githubusercontent.com/23743473/91560104-8c088e00-e939-11ea-8905-d739e8d1623b.png)

**Comment by rmachado-elsevier** [comment]
### Short explanation of the issue

This project depends on `stylelint` to make the (S)CSS/LESS linting. In its turn, `stylelint` depends on another package called `known-css-properties` which has been [updated 17 days ago](https://github.com/stylelint/stylelint/pull/4967) (from the time of this comment 😄 )

So the new (minor) version of stylelint should have the fix necessary and I've created a PR to change it :)
