### ISSUE TITLE
S4670: add parameter for "custom-elements"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/sonar-css#265]
Even after adding the parameter `ignoreTypes` there are still users having problems with the default behavior of this rule. For example when they don't have a single prefix.

It turns out stylelint added an option to ignore custom elements by default: ["custom-elements"](https://stylelint.io/user-guide/rules/selector-type-no-unknown#custom-elements). We should give access to this option and enable it by default.

Request originating from [this community thread](https://community.sonarsource.com/t/stop-flagging-valid-custom-web-component-tag-names-with-s4670/30262/3).

In the meantime there is a workaround by ignoring every element containing a dash with `ignoreTypes`.

**Comment by ahaleiii** [comment]
I see this is closed. Which version of SQ will it be available in? How does one use this change? Is there documentation around this?

**Comment by guillaume-dequenne-sonarsource** [comment]
Hello @ahaleiii,

This change will be available starting from SonarQube 8.8. Rule S4670 will have a new `ignore` parameter that includes `custom-elements` by default. It actually maps to the `ignore` parameter from the corresponding [stylelint rule](https://stylelint.io/user-guide/rules/selector-type-no-unknown#optional-secondary-options) as that's what we are using in the background.

Formally there is no additional documentation besides the parameter description in the rule itself (once updated).

Hope that helps!
