### ISSUE TITLE
Failed to parse json stylelint report: Expected BEGIN_ARRAY but was STRING

### ISSUE THREAD

**Issue by SomethingNew71** [SonarSource/sonar-css#297]
This is still an issue using 
- sonar-css version 1.2.1 
- sonarqube 8.5.1 
- node 12.18.3
- sonar-scanner 3.1.0

I have tried changing the encoding and line endings of the stylelintrc, I have tried different file names (eg. .stylelintrc, .stylelintrc.json, and .stylelintrc.js). None of these have provided a solution and I am at my wit's end trying to get this running in our enterprise application. 

Any idea why this is still happening?

**Comment by andrea-guarino-sonarsource** [comment]
hi @SomethingNew71 ,
Could you please clarify what are the steps to follow to reproduce this error?

**Comment by vilchik-elena** [comment]
We need stylelint report with the issues (like [this one](https://github.com/SonarSource/sonar-css/blob/master/its/plugin/projects/external-report-project/report.json)), not stylelint configuration file
