### ISSUE TITLE
Rule S4664: Selectors of lower specificity should come before overriding selectors of higher specificity

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-css#30]
Implements [RSPEC-4664](https://jira.sonarsource.com/browse/RSPEC-4664)

**Comment by Hilalem** [comment]
Hello ,
Why is the rule inactivated?

**Comment by vilchik-elena** [comment]
@Hilalem the value is debatable, and there are too many issues. Feel free to activate it in custom profile.
