### ISSUE TITLE
 @forward rule of Sass

### ISSUE THREAD

**Issue by jase88** [SonarSource/sonar-css#350]
Sass has a at-rule called `@forward`, see https://sass-lang.com/documentation/at-rules/forward

**Example usage**:
`@forward './icon' as icon-*;`

**Current behaviour**:
- raises a error by default: `Unexpected unknown at-rule "@forward"`

**Expected behaviour**:
- `@Forward` should be added to list of exclusions

**Comment by marierigal** [comment]
Same for the at-rule `@use` https://sass-lang.com/documentation/at-rules/use

**Comment by jase88** [comment]
@marierigal
@use is already implemented in current versions, see
https://github.com/SonarSource/sonar-css/issues/252

**Comment by Maximaximum** [comment]
Any news for the @forward rule? It's still giving errors at SonarCloud

**Comment by mortware** [comment]
+1 for fix please
