### ISSUE TITLE
Unexpected duplicate "display" for flex display with vendor prefix

### ISSUE THREAD

**Issue by taskindrp** [SonarSource/sonar-css#364]
How to bypass this rule for flex display?

![CleanShot 2021-06-24 at 10 04 40](https://user-images.githubusercontent.com/60576788/123217775-9f41a700-d4d3-11eb-91db-17634277abc8.png)

**Comment by vilchik-elena** [comment]
this rule ignores consequent duplicates so I believe your screenshot does not contain one more `display`. If it is so, then just make all of them consequent. Then rule will not report.

**Comment by biveshHalodoc** [comment]
<img width="891" alt="Screenshot 2022-01-12 at 5 36 44 PM" src="https://user-images.githubusercontent.com/78898566/149137390-a22d2d1f-bab8-40bb-a8e7-673ac9dc6a8e.png">

Facing the same issue
