### ISSUE TITLE
Unknown at rule @use

### ISSUE THREAD

**Issue by undergroundwires** [SonarSource/sonar-css#377]
This is a regression bug of  #252 
The warning is there when using `@use`.
Tested in SonarLint `v3.1.0` in VSCode

**Comment by Drywock** [comment]
I experienced the same issue with vscode (same version) and I have it on sonarqube v7.9.5 as well

**Comment by doggodoge** [comment]
I'm seeing this on SonarQube as well.

**Comment by yassin-kammoun-sonarsource** [comment]
> This is a regression bug of #252
> The warning is there when using `@use`.
> Tested in SonarLint `v3.1.0` in VSCode

There is no CSS analysis in SonarLint. I think these warnings are coming from your IDE or another tool.

> I experienced the same issue with vscode (same version) and I have it on sonarqube v7.9.5 as well
> I'm seeing this on SonarQube as well.

Tested with the latest SonarQube, the issue is not flagged anymore.
