### ISSUE TITLE
Analyse CSS inside other language files (html, vue)

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#86]

**Comment by agigleux** [comment]
Do you mean analyzing the content of the <style> tag?

**Comment by vilchik-elena** [comment]
@agigleux yep

**Comment by vilchik-elena** [comment]
We might use https://www.npmjs.com/package/@mapbox/stylelint-processor-arbitrary-tags for both HTML and Vuejs

**Comment by vilchik-elena** [comment]
In fact stylelint is doing that by default so no additional package is required

**Comment by vilchik-elena** [comment]
Note that as of 1.1.1 version JS/TS files (including vue) are not analyzed (see https://github.com/SonarSource/sonar-css/pull/188)
